package interfaces;

//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JTextField;
import java.awt.Color;
import java.awt.Dimension;

import javax.swing.JButton;

/**
 * @author Administrator
 * @created October 23, 2019
 */
public class InterfaceSelection extends JFrame {
   static InterfaceSelection theInterfaceSelection;

   JPanel pnPanelChooseServer;
   JTextField tfTextPort;
   JTextField tfTextAddress;
   JTextField tfServerPort;
   JTextField tfServerAddress;
   JTextField tfClientUsername;
   JButton btButtonServerPoint;
   JButton btButtonServerThread;
   JButton btButtonTCPClient;
   JButton btButtonUDPClient;

   /**
    */
   public static void main(String args[]) {
      try {
         UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      } catch (ClassNotFoundException e) {
      } catch (InstantiationException e) {
      } catch (IllegalAccessException e) {
      } catch (UnsupportedLookAndFeelException e) {
      }
      theInterfaceSelection = new InterfaceSelection();
      theInterfaceSelection.setSize(new Dimension(400, 300));
      theInterfaceSelection.setVisible(true);
   }

   /**
    */
   public InterfaceSelection() {
      super("Selection du serveur / client");

      pnPanelChooseServer = new JPanel();
      GridBagLayout gbPanelChooseServer = new GridBagLayout();
      GridBagConstraints gbcPanelChooseServer = new GridBagConstraints();
      pnPanelChooseServer.setLayout(gbPanelChooseServer);

      tfTextPort = new JTextField();
      tfTextPort.setBackground(new Color(240, 240, 240));
      tfTextPort.setEditable(false);
      tfTextPort.setText("Port :");
      gbcPanelChooseServer.gridx = 0;
      gbcPanelChooseServer.gridy = 0;
      gbcPanelChooseServer.gridwidth = 6;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(tfTextPort, gbcPanelChooseServer);
      pnPanelChooseServer.add(tfTextPort);

      tfTextAddress = new JTextField();
      tfTextAddress.setBackground(new Color(240, 240, 240));
      tfTextAddress.setEditable(false);
      tfTextAddress.setText("Adresse ip :");
      gbcPanelChooseServer.gridx = 6;
      gbcPanelChooseServer.gridy = 0;
      gbcPanelChooseServer.gridwidth = 9;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(tfTextAddress, gbcPanelChooseServer);
      pnPanelChooseServer.add(tfTextAddress);

      tfServerPort = new JTextField();
      tfServerPort.setText("3000");
      gbcPanelChooseServer.gridx = 0;
      gbcPanelChooseServer.gridy = 2;
      gbcPanelChooseServer.gridwidth = 6;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(tfServerPort, gbcPanelChooseServer);
      pnPanelChooseServer.add(tfServerPort);

      tfServerAddress = new JTextField();
      tfServerAddress.setText("localhost");
      gbcPanelChooseServer.gridx = 6;
      gbcPanelChooseServer.gridy = 2;
      gbcPanelChooseServer.gridwidth = 9;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(tfServerAddress, gbcPanelChooseServer);
      pnPanelChooseServer.add(tfServerAddress);

      tfClientUsername = new JTextField();
      tfClientUsername.setText("username");
      gbcPanelChooseServer.gridx = 0;
      gbcPanelChooseServer.gridy = 8;
      gbcPanelChooseServer.gridwidth = 6;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(tfClientUsername, gbcPanelChooseServer);
      pnPanelChooseServer.add(tfClientUsername);

      btButtonServerPoint = new JButton("Serveur accès unique");
      gbcPanelChooseServer.gridx = 6;
      gbcPanelChooseServer.gridy = 4;
      gbcPanelChooseServer.gridwidth = 9;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(btButtonServerPoint, gbcPanelChooseServer);
      pnPanelChooseServer.add(btButtonServerPoint);
      btButtonServerPoint.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btButtonServerPointClicked(evt);
         }
      });

      btButtonServerThread = new JButton("Serveur à thread");
      gbcPanelChooseServer.gridx = 6;
      gbcPanelChooseServer.gridy = 6;
      gbcPanelChooseServer.gridwidth = 9;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(btButtonServerThread, gbcPanelChooseServer);
      pnPanelChooseServer.add(btButtonServerThread);
      btButtonServerThread.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btButtonServerThreadClicked(evt);
         }
      });

      btButtonTCPClient = new JButton("Client TCP");
      gbcPanelChooseServer.gridx = 6;
      gbcPanelChooseServer.gridy = 8;
      gbcPanelChooseServer.gridwidth = 9;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(btButtonTCPClient, gbcPanelChooseServer);
      pnPanelChooseServer.add(btButtonTCPClient);
      btButtonTCPClient.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btButtonTCPClientClicked(evt);
         }
      });

      btButtonUDPClient = new JButton("Communication multicast");
      gbcPanelChooseServer.gridx = 6;
      gbcPanelChooseServer.gridy = 10;
      gbcPanelChooseServer.gridwidth = 9;
      gbcPanelChooseServer.gridheight = 2;
      gbcPanelChooseServer.fill = GridBagConstraints.BOTH;
      gbcPanelChooseServer.weightx = 1;
      gbcPanelChooseServer.weighty = 0;
      gbcPanelChooseServer.anchor = GridBagConstraints.NORTH;
      gbPanelChooseServer.setConstraints(btButtonUDPClient, gbcPanelChooseServer);
      pnPanelChooseServer.add(btButtonUDPClient);
      btButtonUDPClient.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btButtonUDPClientClicked(evt);
         }
      });

      setDefaultCloseOperation(EXIT_ON_CLOSE);

      setContentPane(pnPanelChooseServer);
      pack();
      setVisible(true);
   }

   private void btButtonServerPointClicked(java.awt.event.MouseEvent evt) {
      theInterfaceSelection.setVisible(false);
      InterfaceServer theInterfaceServer = new InterfaceServer();
      theInterfaceServer.start(tfServerPort.getText(), 1);
      theInterfaceServer.setSize(new Dimension(400, 300));
      theInterfaceServer.setVisible(true);
   }

   private void btButtonServerThreadClicked(java.awt.event.MouseEvent evt) {
      theInterfaceSelection.setVisible(false);
      InterfaceServer theInterfaceServer = new InterfaceServer();
      theInterfaceServer.start(tfServerPort.getText(), 2);
      theInterfaceServer.setSize(new Dimension(400, 300));
      theInterfaceServer.setVisible(true);
   }

   private void btButtonTCPClientClicked(java.awt.event.MouseEvent evt) {
      theInterfaceSelection.setVisible(false);
      InterfaceClient theInterfaceClient = new InterfaceClient();
      theInterfaceClient.start(tfServerAddress.getText(), tfServerPort.getText(), tfClientUsername.getText(), 1);
      theInterfaceClient.setSize(new Dimension(400, 300));
      theInterfaceClient.setVisible(true);
   }

   private void btButtonUDPClientClicked(java.awt.event.MouseEvent evt) {
      theInterfaceSelection.setVisible(false);
      InterfaceClient theInterfaceClient = new InterfaceClient();
      theInterfaceClient.start(tfServerAddress.getText(), tfServerPort.getText(), tfClientUsername.getText(), 2);
      theInterfaceClient.setSize(new Dimension(400, 300));
      theInterfaceClient.setVisible(true);
   }
}
