package interfaces;
//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import stream.EchoClient;
import udp.EchoClientUDP;

import javax.swing.JPanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;

import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JButton;

/**
 * @author Administrator
 * @created October 23, 2019
 */
public class InterfaceClient extends JFrame {
   static InterfaceClient theInterfaceClient;

   JPanel pnPanelClient;
   JTextArea taAreaReceivedMessages;
   JTextField tfTextMessage;
   JButton btButtonSendMessage;
   JButton btButtonDisconnect;
   EchoClient clientTCP;
   EchoClientUDP clientUDP;
   Integer type;
   String username;

   /**
    */
   public static void main(String args[]) {
      try {
         UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      } catch (ClassNotFoundException e) {
      } catch (InstantiationException e) {
      } catch (IllegalAccessException e) {
      } catch (UnsupportedLookAndFeelException e) {
      }
      theInterfaceClient = new InterfaceClient();
   }

   public void start(String ip, String port, String usrname, Integer type) {
      this.type = type;
      username = usrname;
      if (type == 1) {
         clientTCP = new EchoClient();
         clientTCP.connect(ip, port);
         clientTCP.setOutput(this);
         clientTCP.sendMessage(username + " joined the chat");
      }
      if (type == 2) {
         clientUDP = new EchoClientUDP();
      }
   }

   public void addMessage(String line){
      taAreaReceivedMessages.append(line + "\n");
   }

   /**
    */
   public InterfaceClient() {
      super("Interface Client");

      pnPanelClient = new JPanel();
      GridBagLayout gbPanelClient = new GridBagLayout();
      GridBagConstraints gbcPanelClient = new GridBagConstraints();
      pnPanelClient.setLayout(gbPanelClient);

      taAreaReceivedMessages = new JTextArea(2, 10);
      taAreaReceivedMessages.setEditable(false);
      JScrollPane scpAreaReceivedMessages = new JScrollPane(taAreaReceivedMessages);
      gbcPanelClient.gridx = 1;
      gbcPanelClient.gridy = 1;
      gbcPanelClient.gridwidth = 27;
      gbcPanelClient.gridheight = 15;
      gbcPanelClient.fill = GridBagConstraints.BOTH;
      gbcPanelClient.weightx = 1;
      gbcPanelClient.weighty = 1;
      gbcPanelClient.anchor = GridBagConstraints.NORTH;
      gbPanelClient.setConstraints(scpAreaReceivedMessages, gbcPanelClient);
      pnPanelClient.add(scpAreaReceivedMessages);

      tfTextMessage = new JTextField();
      gbcPanelClient.gridx = 1;
      gbcPanelClient.gridy = 17;
      gbcPanelClient.gridwidth = 13;
      gbcPanelClient.gridheight = 2;
      gbcPanelClient.fill = GridBagConstraints.BOTH;
      gbcPanelClient.weightx = 1;
      gbcPanelClient.weighty = 0;
      gbcPanelClient.anchor = GridBagConstraints.NORTH;
      gbPanelClient.setConstraints(tfTextMessage, gbcPanelClient);
      pnPanelClient.add(tfTextMessage);

      btButtonSendMessage = new JButton("Envoyer");
      gbcPanelClient.gridx = 15;
      gbcPanelClient.gridy = 17;
      gbcPanelClient.gridwidth = 5;
      gbcPanelClient.gridheight = 2;
      gbcPanelClient.fill = GridBagConstraints.BOTH;
      gbcPanelClient.weightx = 1;
      gbcPanelClient.weighty = 0;
      gbcPanelClient.anchor = GridBagConstraints.NORTH;
      gbPanelClient.setConstraints(btButtonSendMessage, gbcPanelClient);
      pnPanelClient.add(btButtonSendMessage);
      btButtonSendMessage.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btButtonSendMessageClicked(evt);
         }
      });

      btButtonDisconnect = new JButton("Deconnexion");
      gbcPanelClient.gridx = 21;
      gbcPanelClient.gridy = 17;
      gbcPanelClient.gridwidth = 7;
      gbcPanelClient.gridheight = 2;
      gbcPanelClient.fill = GridBagConstraints.BOTH;
      gbcPanelClient.weightx = 1;
      gbcPanelClient.weighty = 0;
      gbcPanelClient.anchor = GridBagConstraints.NORTH;
      gbPanelClient.setConstraints(btButtonDisconnect, gbcPanelClient);
      pnPanelClient.add(btButtonDisconnect);
      btButtonDisconnect.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            btButtonDisconnectClicked(evt);
         }
      });

      setDefaultCloseOperation(EXIT_ON_CLOSE);

      setContentPane(pnPanelClient);
      pack();
      setVisible(true);
   }

   private void btButtonSendMessageClicked(java.awt.event.MouseEvent evt) {
      if (type == 1) {
         clientTCP.sendMessage(tfTextMessage.getText());
         tfTextMessage.setText("");
      }
      if(type==2)
      {
      //clientUDP;
      }
   }

   private void btButtonDisconnectClicked(java.awt.event.MouseEvent evt) {
      if (type == 1) {
         clientTCP = new EchoClient();
         try {
            clientTCP.close();
         } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
         }
      }
      if(type==2)
      {
      //clientUDP;
      }
   }
}
