package interfaces;

//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import stream.EchoServer;
import stream.EchoServerMultiThreaded;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

import java.awt.Color;
import java.awt.Dimension;

/**
 * @author Administrator
 * @created October 23, 2019
 */
public class InterfaceServer extends JFrame {
   static InterfaceServer theInterfaceServer;

   JPanel pnServerLogs;
   JTextArea tfTextLog;
   Integer type;
   EchoServer serverPoint;
   EchoServerMultiThreaded serverThread;

   /**
    */
   public static void main(String args[]) {
      try {
         UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      } catch (ClassNotFoundException e) {
      } catch (InstantiationException e) {
      } catch (IllegalAccessException e) {
      } catch (UnsupportedLookAndFeelException e) {
      }
      theInterfaceServer = new InterfaceServer();
      theInterfaceServer.setSize(new Dimension(400, 300));
      theInterfaceServer.setVisible(true);
   }

   public void start(String port, Integer type) {
      this.type = type;
      if (type == 1) {
         serverPoint = new EchoServer();
         serverPoint.initial(port, this);
         serverPoint.start();
      }
      if (type == 2) {
         serverThread = new EchoServerMultiThreaded();
         serverThread.start(port);
      }
   }

   public void addLog(String log) {
      tfTextLog.setText(tfTextLog.getText() + log);
   }

   /**
    */
   public InterfaceServer() {
      super("Interface Serveur");

      pnServerLogs = new JPanel();
      GridBagLayout gbServerLogs = new GridBagLayout();
      GridBagConstraints gbcServerLogs = new GridBagConstraints();
      pnServerLogs.setLayout(gbServerLogs);

      tfTextLog = new JTextArea();
      tfTextLog.setBackground(new Color(240, 240, 240));
      tfTextLog.setEditable(false);
      JScrollPane scpAreaReceivedMessages = new JScrollPane(tfTextLog);
      gbcServerLogs.gridx = 1;
      gbcServerLogs.gridy = 1;
      gbcServerLogs.gridwidth = 27;
      gbcServerLogs.gridheight = 15;
      gbcServerLogs.fill = GridBagConstraints.BOTH;
      gbcServerLogs.weightx = 1;
      gbcServerLogs.weighty = 1;
      gbcServerLogs.anchor = GridBagConstraints.NORTH;
      gbServerLogs.setConstraints(scpAreaReceivedMessages, gbcServerLogs);
      pnServerLogs.add(scpAreaReceivedMessages);

      setDefaultCloseOperation(EXIT_ON_CLOSE);

      setContentPane(pnServerLogs);
      pack();
      setVisible(true);
   }
}
